force-app/main/default/objects/passport__c/passport__c.object-meta.xml
<CustomObject>
    <label>passport</label>
    <nameField>
        <displayFormat>p-{0000}</displayFormat>
        <label>passport Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>passports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/passport__c/fields/Expired_date__c.field-meta.xml
<CustomField>
    <fullName>Expired_date__c</fullName>
    <label>Date of Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/passport__c/fields/Issued_date__c.field-meta.xml
<CustomField>
    <fullName>Issued_date__c</fullName>
    <label>Date of Issue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/passport__c/fields/Name_as_per_Passport__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_Passport__c</fullName>
    <description>Name As per passport</description>
    <formula>First_Name__c &amp; &quot; &quot; &amp; Last_name__c &amp; &quot; &quot; &amp; Surname__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Name As per passport</inlineHelpText>
    <label>Name as per Passport</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/passport__c/fields/passport_Number__c.field-meta.xml
<CustomField>
    <fullName>passport_Number__c</fullName>
    <label>passport Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/passport__c/fields/Place_of_Issue__c.field-meta.xml
<CustomField>
    <fullName>Place_of_Issue__c</fullName>
    <label>Place of Issue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Salem</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Cochin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>TEXT (Salutation__c)  &amp; &quot; &quot; &amp;    First_Name__c  &amp; &quot; &quot; &amp;   Middle_Name__c  &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name of the user</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PassPortPreview.cls
public class PassPortPreview {
     @AuraEnabled(cacheable=true)
    public static List<Passport__c> getPassportRecords(String userName) {
        List<Passport__c> passportRecords = new List<Passport__c>();
        
        // Query User records
        List<User__c> users = [SELECT Id, Name FROM User__c];
        
        // Query Passport records
        List<Passport__c> passports = [SELECT Id, Name__c,	Name_as_per_Passport__c ,passport_Number__c,Place_of_Issue__c,Expired_date__c,Issued_date__c FROM Passport__c WHERE Name__c = :userName];
        
        // Match records based on Name
        for (User__c user : users) {
            for (Passport__c passport : passports) {
                if (user.Name == passport.Name__c) {
                    passportRecords.add(passport);
                }
            }
        }
        
        return passportRecords;
    }
}