force-app/main/default/objects/Time_Tracker__c/Time_Tracker__c.object-meta.xml
<CustomObject>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{0000}</displayFormat>
        <label>Time Tracker Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>TEXT (Salutation__c)  &amp; &quot; &quot; &amp;    First_Name__c  &amp; &quot; &quot; &amp;   Middle_Name__c  &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name of the user</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimeTrackerPreview.cls
public with sharing class TimeTrackerPreview {
    @AuraEnabled(cacheable=true)
    public static List<Time_Tracker__c> getTimeTrackerRecords(String userName) {
        List<Time_Tracker__c> timeTrackerRecords = new List<Time_Tracker__c>();
        
        // Query User records
        List<User__c> users = [SELECT Id, Name FROM User__c];
        
        // Query Time Tracker records
        List<Time_Tracker__c> timeTrackers = [SELECT Id, Name__c, Start_Time__c, End_Time__c FROM Time_Tracker__c where name__c=:userName order by Start_Time__c desc limit 7 ];
        
        // Match records based on Name
        for (User__c user : users) {
            for (Time_Tracker__c timeTracker : timeTrackers) {
                if (user.Name == timeTracker.Name__c) {
                    timeTrackerRecords.add(timeTracker);
                }
            }
        }
        
        return timeTrackerRecords;
    }
}