force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Timesheet Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>Total Hours</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Work_Done__c.field-meta.xml
<CustomField>
    <fullName>Work_Done__c</fullName>
    <label>Work Done</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>TEXT (Salutation__c)  &amp; &quot; &quot; &amp;    First_Name__c  &amp; &quot; &quot; &amp;   Middle_Name__c  &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name of the user</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <inlineHelpText>Kindly Fill out the Quadrobay Email.</inlineHelpText>
    <label>Username</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimeSheetController.cls
public with sharing class TimeSheetController {
    @AuraEnabled
    public static Boolean insertNameRecord(String name) {
        List<TimeSheet__c> existingRecords = [SELECT Id FROM TimeSheet__c WHERE Name__c = :name];
        return !existingRecords.isEmpty();
    }

    @AuraEnabled(cacheable=true)
    public static User__c getUserInfo(String username) {
        try {
            // Query the User__c object to fetch the Name based on the Username__c field
            return [SELECT Id, Name, Employee_Id__c FROM User__c WHERE Username__c = :username LIMIT 1];
        } catch (Exception ex) {
            // Handle any errors that occurred during the query
            System.debug('Error fetching user info: ' + ex.getMessage());
            return null;
        }
    }

    

  @AuraEnabled
    public static void saveTimeSheetRecord(String name, String employeeId, String description, String workdone, String projectname,Decimal totalhours ) {
        try {
            if (String.isNotBlank(name)) { // Check if name is not null or empty
                Timesheet__c timesheetRecord = new Timesheet__c(
                    Name__c = name,
                    Employee_Id__c = employeeId,
                    Description__c = description,
                     Work_Done__c = workdone,
                    Project_Name__c = projectname,
                    Total_Hours__c = totalhours
                );
                insert timesheetRecord;
                System.debug('Timesheet Record Inserted: ' + timesheetRecord);
            }
        } catch (Exception ex) {
            System.debug('Error Message: ' + ex.getMessage());
            System.debug('Stack Trace: ' + ex.getStackTraceString());
            throw ex;
        }
    }
}