force-app/main/default/objects/Food_Details__c/Food_Details__c.object-meta.xml
<CustomObject>
    <label>Food Details</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stay_Details__c/Stay_Details__c.object-meta.xml
<CustomObject>
    <label>Stay Details</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stay Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Detail__c/Travel_Detail__c.object-meta.xml
<CustomObject>
    <label>Travel Detail</label>
    <nameField>
        <label>Employee name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Travel_Detail__c/fields/Mode_of_travel__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_travel__c</fullName>
    <inlineHelpText>Select the way of travel to your Destiniy</inlineHelpText>
    <label>Mode of travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rental car/bike</fullName>
            </value>
            <value>
                <fullName>Bus</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Mini cab/Taxi</fullName>
            </value>
            <value>
                <fullName>Airfare</fullName>
            </value>
            <value>
                <fullName>Fuel charge</fullName>
            </value>
            <value>
                <fullName>Toll fare</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FoodDetailsController.cls
public with sharing class FoodDetailsController {
    @AuraEnabled
    public static Id saveFoodDetails(Food_Details__c foodDetailsRec, String file, String fileName) {
        Id foodDetailsId;
        try {
            // Insert the Food_Details__c record
            Insert foodDetailsRec;
            foodDetailsId = foodDetailsRec.Id;
    
            // Decode and insert the file as a ContentVersion record
            String base64File = EncodingUtil.urlDecode(file, 'UTF-8');
            ContentVersion contentVersionRec = new ContentVersion();
            contentVersionRec.Title = fileName;
            contentVersionRec.PathOnClient = '/' + fileName;
            contentVersionRec.FirstPublishLocationId = foodDetailsRec.Id;
            contentVersionRec.VersionData = EncodingUtil.base64Decode(base64File);
            contentVersionRec.IsMajorVersion = true;
            Insert contentVersionRec;
        } catch (Exception ex) {
            system.debug('Exception ===> ' + ex.getMessage());
        }
        return foodDetailsId;
    }
     
    @AuraEnabled
    public static String saveStayDetails(Stay_Details__c stayRec, String file, String fileName) {
        String stayId;
        try {
            Insert stayRec;
            stayId = stayRec.Id;

            String base64File = EncodingUtil.urlDecode(file, 'UTF-8');

            ContentVersion contentVersionRec = new ContentVersion();
            contentVersionRec.Title = fileName;
            contentVersionRec.PathOnClient = '/' + fileName;
            contentVersionRec.FirstPublishLocationId = stayRec.Id;
            contentVersionRec.VersionData = EncodingUtil.base64Decode(base64File);
            contentVersionRec.IsMajorVersion = true;

            Insert contentVersionRec;
        } catch (Exception ex) {
            System.debug('Exception ===> ' + ex.getMessage());
        }
        return stayId;
    }
        @AuraEnabled(cacheable=true)
        public static List<String> getModeOfTravelPicklistValues() {
            List<String> picklistValues = new List<String>();
            Schema.DescribeFieldResult fieldResult = Travel_Detail__c.Mode_of_travel__c.getDescribe();
            for (Schema.PicklistEntry entry : fieldResult.getPicklistValues()) {
                picklistValues.add(entry.getLabel());
            }
            return picklistValues;
        }
        
        @AuraEnabled
        public static Id saveTravelDetail(Travel_Detail__c travelDetailRec, String file, String fileName) {
            Id travelDetailId;
            try {
                insert travelDetailRec;
                travelDetailId = travelDetailRec.Id;
    
                String base64File = EncodingUtil.urlDecode(file, 'UTF-8');
    
                ContentVersion contentVersionRec = new ContentVersion();
                contentVersionRec.Title = fileName;
                contentVersionRec.PathOnClient = '/' + fileName;
                contentVersionRec.FirstPublishLocationId = travelDetailRec.Id;
                contentVersionRec.VersionData = EncodingUtil.base64Decode(base64File);
                contentVersionRec.IsMajorVersion = true;
                insert contentVersionRec;
            } catch (Exception ex) {
                system.debug('Exception ===> ' + ex.getMessage());
            }
            return travelDetailId;
        }
}