force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Count__c.field-meta.xml
<CustomField>
    <fullName>Leave_Count__c</fullName>
    <label>Leave Count</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
            <value>
                <fullName>Casual Leave</fullName>
            </value>
            <value>
                <fullName>Marriage Leave</fullName>
            </value>
            <value>
                <fullName>Bereavement Leave</fullName>
            </value>
            <value>
                <fullName>Earned Leave</fullName>
            </value>
            <value>
                <fullName>Loss Of Pay</fullName>
            </value>
            <value>
                <fullName>Work From Home</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Reason_for_Leave__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leave__c</fullName>
    <label>Reason for Leave</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Remaining_Leave__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Leave__c</fullName>
    <label>Remaining Leave</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Tracker__c/Time_Tracker__c.object-meta.xml
<CustomObject>
    <label>Time Tracker</label>
    <nameField>
        <displayFormat>TT-{0000}</displayFormat>
        <label>Time Tracker Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Tracker__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Tracker__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <formula>TEXT(FLOOR((End_Time__c - Start_Time__c) * 24)) &amp; &quot; Hours &quot; &amp;
TEXT(FLOOR(MOD((End_Time__c - Start_Time__c) * 1440, 60))) &amp; &quot; Minutes&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Hours</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Timesheet Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <label>Total Hours</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Work_Done__c.field-meta.xml
<CustomField>
    <fullName>Work_Done__c</fullName>
    <label>Work Done</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LwcSearchFilterCtrl.cls
public with sharing class LwcSearchFilterCtrl {
    @AuraEnabled
    public static List<sObject> getRecords(String objectName,string name,string employeeid,Date startDate,Date endDate) {
        System.debug('ObjectecName'+objectName);
        System.debug('ObjectecName'+name);
        System.debug('employeeid'+employeeid);
        System.debug('startDate'+startDate);
        System.debug('endDate'+endDate);
        String query ='SELECT Employee_Id__c, Name__c,';
        if (objectName == null) {
            return new List<sObject>();
        }
        if (objectName ==  'Time_Tracker__c') {
            query +=  ' Start_Time__c, End_Time__c, Total_Hours__c, CreatedDate FROM Time_Tracker__c';
            
        } if (objectName ==  'Timesheet__c') {
            query +=  ' Project_Name__c, Total_Hours__c, Date__c, Work_Done__c, CreatedDate FROM Timesheet__c';
            
        }  if (objectName ==  'Leave_Request__c') {
            query +=  ' Leave_Type__c, Leave_Count__c, Reason_for_Leave__c, Remaining_Leave__c, CreatedDate FROM Leave_Request__c';
        } if(name!=null &&name!='' &&employeeid!=null &&startDate!=null && endDate!=null){
            query+=' Where Name__c=:name AND Employee_Id__c=:employeeid AND CreatedDate>=:startDate AND CreatedDate<=:endDate';
            System.debug('query'+query);
        } else if(name!=null &&name!=''){
            query+=' Where Name__c=:name';
            System.debug('datequery'+query);
        }
        
        return Database.query(query);
    }
}