force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Reason_for_Leave__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Leave__c</fullName>
    <label>Reason for Leave</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>TEXT (Salutation__c)  &amp; &quot; &quot; &amp;    First_Name__c  &amp; &quot; &quot; &amp;   Middle_Name__c  &amp; &quot; &quot; &amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name of the user</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Bench</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <inlineHelpText>Kindly Fill out the Quadrobay Email.</inlineHelpText>
    <label>Username</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/leaveTrackerController.cls
public class leaveTrackerController {
               @AuraEnabled(cacheable=true)
    public static User__c getUserInfo(String username) {
        try {
            // Query the User__c object to fetch the Name based on the Username__c field
            return [SELECT Id, Name FROM User__c WHERE Username__c = :username LIMIT 1];
        } catch (Exception ex) {
            // Handle any errors that occurred during the query
            System.debug('Error fetching user info: ' + ex.getMessage());
            return null;
        }
    }
    
        @AuraEnabled(cacheable=true)
    public static List<Leave_Request__c> getLeaveRequests(){
        try {
            List<Leave_Request__c> myLeaves=new List<Leave_Request__c>();
            myLeaves=[SELECT Id,Name__c ,From__c,To__c,Reason_for_Leave__c,Status__c FROM Leave_Request__c
           ];
            return myLeaves;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}