force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/Date_Of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <inlineHelpText>Enter a Proper Date Of Birth</inlineHelpText>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Date_Of_Joining__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Joining__c</fullName>
    <label>Date Of Joining</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Associate consultant</fullName>
            </value>
            <value>
                <fullName>Software Testing Engineer</fullName>
            </value>
            <value>
                <fullName>Senior Consultant</fullName>
            </value>
            <value>
                <fullName>Trainee Consultant</fullName>
            </value>
            <value>
                <fullName>Consultant - Oracle</fullName>
            </value>
            <value>
                <fullName>Trainee - Oracle</fullName>
            </value>
            <value>
                <fullName>Trainee - RPA</fullName>
            </value>
            <value>
                <fullName>Delivery Head</fullName>
            </value>
            <value>
                <fullName>Tech Lead</fullName>
            </value>
            <value>
                <fullName>Office Assistant</fullName>
            </value>
            <value>
                <fullName>Operations Manager</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Software Test Engineer</fullName>
            </value>
            <value>
                <fullName>Sr. Manager Finance</fullName>
            </value>
            <value>
                <fullName>Sr. Finance Executive</fullName>
            </value>
            <value>
                <fullName>Trainee - SFDC</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Sr. Oracle Functional Consultant</fullName>
            </value>
            <value>
                <fullName>HR Executive</fullName>
            </value>
            <value>
                <fullName>Software Engineer</fullName>
            </value>
            <value>
                <fullName>Software consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User__c/fields/Driver_s_License_Number__c.field-meta.xml
<CustomField>
    <fullName>Driver_s_License_Number__c</fullName>
    <label>Driving License Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Personal Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <label>Employee Id</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afghan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Anguillan</fullName>
            </value>
            <value>
                <fullName>Argentine</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bermudian</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Botswanan</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>British Virgin Islander</fullName>
            </value>
            <value>
                <fullName>Bruneian</fullName>
            </value>
            <value>
                <fullName>Bulgarian</fullName>
            </value>
            <value>
                <fullName>Burkinan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User__c/fields/P_UAN_Number__c.field-meta.xml
<CustomField>
    <fullName>P_UAN_Number__c</fullName>
    <label>UAN Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <inlineHelpText>&quot;It must contain at least one uppercase letter, one lowercase letter, and one number, with a minimum length of 8 characters.&quot;</inlineHelpText>
    <label>Password</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/SIN_Number__c.field-meta.xml
<CustomField>
    <fullName>SIN_Number__c</fullName>
    <label>SIN Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Skill_Set__c.field-meta.xml
<CustomField>
    <fullName>Skill_Set__c</fullName>
    <label>Skill Set</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User__c/fields/SSN_Number__c.field-meta.xml
<CustomField>
    <fullName>SSN_Number__c</fullName>
    <label>SSN Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Bench</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <inlineHelpText>Kindly Fill out the Quadrobay Email.</inlineHelpText>
    <label>Username</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoginController.cls
public with sharing class LoginController {
    @AuraEnabled(cacheable=true)
    public static Boolean checkCredentials(String username, String password) {
        // Query the Login_Credentials__c custom object for the given username
        List<User__c> credentialsList = [SELECT Id, Password__c FROM User__c WHERE Username__c = :username LIMIT 1];

        if (!credentialsList.isEmpty()) {
            // If credentials are found, compare the provided password with the stored password
            User__c credentials = credentialsList[0];
            return credentials.Password__c == password;
        }
        // Return false if no credentials found for the given username
        return false;
    }
    
        @AuraEnabled(cacheable=true)
    public static User__c getUserInfo(String username, string name, string employeeid,string designation, date dateofjoining, string role,string email, date dateofbirth,string drivinglicensenumber, date licenseexpirydate, string ssnnumber, string sinnumber,string nationality, string status, string uannumber ) {
        try {
            // Query the User__c object to fetch the Name based on the Username__c field
            return [SELECT Id, Name, Employee_Id__c ,Designation__c, Date_Of_Joining__c, Role__c, Email__c, Date_Of_Birth__c,Driver_s_License_Number__c, License_Expiry_Date__c, SSN_Number__c, SIN_Number__c, Nationality__c, Status__c,Skill_Set__c,	P_UAN_Number__c FROM User__c WHERE Username__c = :username LIMIT 1];
        } catch (Exception ex) {
            // Handle any errors that occurred during the query
            System.debug('Error fetching user info: ' + ex.getMessage());
            return null;
        }
    }
    
    
}